Call_Board/CallBoard/CallBoard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Call_Board/CallBoard/board/urls.py
from django.urls import path
from .views import index, other_page, category_ads, AdvertCreateView, LoginView, profile, LogoutView, ProfileEditView, \
    PasswordEditView, RegisterDoneView, RegisterView, user_activate, ProfileDeleteView, ad_detail, profile_ad_add, \
    profile_ad_detail, profile_ad_edit, profile_ad_delete

app_name = 'board'
urlpatterns = [
    path('add/', AdvertCreateView.as_view(), name='add'),
    path('<int:category_pk>/<int:pk>/', ad_detail, name='ad_detail'),
    path('<int:pk>/', category_ads, name='category_ads'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/profile/add/', profile_ad_add, name='profile_ad_add'),
    path('accounts/profile/<int:pk>/', profile_ad_detail, name='profile_ad_detail'),
    path('accounts/profile/edit/<int:pk>/', profile_ad_edit, name='profile_ad_edit'),
    path('accounts/profile/delete/<int:pk>/', profile_ad_delete, name='profile_ad_delete'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('accounts/password/edit/', PasswordEditView.as_view(), name='password_edit'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/activate/<str:sign>/', user_activate, name='activate'),
    path('accounts/profile/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
]

Call_Board/CallBoard/board/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from board.utilites import get_timestamp_path

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Слать оповещения о новых комментариях?')

    def delete(self, *args, **kwargs):
        for ad in self.ad_set.all():
            ad.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass

class Advert(models.Model):
    category = models.ForeignKey('Category', null=True,
                                 on_delete=models.PROTECT,
                                 verbose_name='Категория')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Описание')
    contacts = models.TextField(verbose_name='Контакты')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path,
                              verbose_name='Изображение')
    author = models.ForeignKey(AdvUser, default='', on_delete=models.CASCADE,
                               verbose_name='Автор объявления')
    is_active = models.BooleanField(default=True, db_index=True,
                                    verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Опубликовано')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-created_at']

class AdditionalImage(models.Model):
    ad = models.ForeignKey(Advert, on_delete=models.CASCADE,
                           verbose_name='Объявление')
    image = models.ImageField(upload_to=get_timestamp_path,
                              verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True,
                            db_index=True, verbose_name='Категория')
    # order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ['name']

class Comment(models.Model):
    ad = models.ForeignKey(Advert, on_delete=models.CASCADE,
                           verbose_name='Объявление')
    author = models.CharField(max_length=30, verbose_name='Автор')
    content = models.TextField(verbose_name='Содержание')
    is_active = models.BooleanField(default=True, db_index=True,
                                    verbose_name='Выводить на экран?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Опубликован')

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['created_at']

Call_Board/CallBoard/board/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Advert, AdvUser, AdditionalImage, Comment
from .signals import post_register


class AdvertForm(ModelForm):
    class Meta:
        model = Advert
        fields = '__all__'

class ProfileEditForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name',
                  'send_messages')

class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        post_register.send(RegisterForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

class AdForm(forms.ModelForm):
    class Meta:
        model = Advert
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = forms.inlineformset_factory(Advert, AdditionalImage, fields='__all__')

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}

Call_Board/CallBoard/board/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.core.signing import BadSignature
from django.db.models import Q
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader, TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, DeleteView
from .forms import AdvertForm, ProfileEditForm, RegisterForm, SearchForm, AdForm, AIFormSet, UserCommentForm
from .models import Advert, Category, AdvUser, Comment
from .utilites import signer


def index(request):
    ads = Advert.objects.filter(is_active=True).select_related('category')[:10]
    categories = Category.objects.all()
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'categories': categories, 'page': page, 'ads': page.object_list}
    return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def category_ads(request, pk):
    category = get_object_or_404(Category, pk=pk)
    ads = Advert.objects.filter(is_active=True, category=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    categories = Category.objects.all()
    context = {'category': category, 'categories': categories, 'page': page, 'ads': page.object_list,
               'form': form}
    return render(request, 'main/category_ads.html', context)


def ad_detail(request, category_pk, pk):
    ad = Advert.objects.get(pk=pk)
    initial = {'ad': ad.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Комментарий добавлен')
            return redirect(request.get_full_path_info())
        else:
            form = c_form
            messages.add_message(request, messages.WARNING,
                                 'Комментарий не добавлен')
    ais = ad.additionalimage_set.all()
    comments = Comment.objects.filter(ad=pk, is_active=True)
    categories = Category.objects.all()
    context = {'ad': ad, 'ais': ais, 'categories': categories, 'comments': comments, 'form': form}
    return render(request, 'main/ad_detail.html', context)


class AdvertCreateView(CreateView):
    template_name = 'main/ad_create.html'
    form_class = AdvertForm
    success_url = reverse_lazy('board:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ads'] = Advert.objects.filter(category=context['category_id'])
        context['categories'] = Category.objects.all()
        context['current_category'] = Category.objects.all()
        return context


class LoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    ads = Advert.objects.filter(author=request.user.pk)
    context = {'ads': ads}
    return render(request, 'main/profile.html', context)


class LogoutView(LogoutView):
    pass


class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/profile_edit.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('board:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_edit.html'
    success_url = reverse_lazy('board:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterView(CreateView):
    model = AdvUser
    template_name = 'main/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('board:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/activation_failed.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/activation_done_earlier.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/profile_delete.html'
    success_url = reverse_lazy('board:index')
    success_message = 'Пользователь удален'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


@login_required
def profile_ad_detail(request, pk):
    ad = get_object_or_404(Advert, pk=pk)
    ais = ad.additionalimage_set.all()
    comments = Comment.objects.filter(ad=pk, is_active=True)
    context = {'ad': ad, 'ais': ais, 'comments': comments}
    return render(request, 'main/profile_ad_detail.html', context)


@login_required
def profile_ad_add(request):
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS,
                                     'Объявление добавлено')
                return redirect('board:profile')
    else:
        form = AdForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_add.html', context)


@login_required
def profile_ad_edit(request, pk):
    ad = get_object_or_404(Advert, pk=pk)
    if request.method == 'POST':
        form = AdvertForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            ad = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS,
                                     'Объявление исправлено')
                return redirect('board:profile')
    else:
        form = AdvertForm(instance=ad)
        formset = AIFormSet(instance=ad)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_ad_edit.html', context)


@login_required
def profile_ad_delete(request, pk):
    ad = get_object_or_404(Advert, pk=pk)
    if request.method == 'POST':
        ad.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('board:profile')
    else:
        context = {'ad': ad}
        return render(request, 'main/profile_ad_delete.html', context)

Call_Board/CallBoard/board/templates/main/about.html
{% extends 'layout/basic.html' %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Интернет-ресурс для фанатского сервера одной известной MMORPG</p>
<p>Все права защищены.</p>
{% endblock %}

Call_Board/CallBoard/board/templates/main/activation_done.html
{% extends 'layout/basic.html' %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'board:login' %}">Войти на сайт</a></p>
{% endblock %}

Call_Board/CallBoard/board/templates/main/activation_done_earlier.html
{% extends 'layout/basic.html' %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'board:login' %}">Войти на сайт</a></p>
{% endblock %}

Call_Board/CallBoard/board/templates/main/ad_create.html
{% extends "layout/basic.html" %}

{% block title %}Добавить объявление{% endblock %}

{% block content %}
<h2>Добавить объявление</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

Call_Board/CallBoard/board/templates/main/ad_detail.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}{{ ad.title }} - {{ ad.category.name }}{% endblock %}

{% block content %}
<div class="row mt-3">
    {% if ad.image %}
    <div class="col-md-auto">
        <img src="{{ ad.image.url }}" class="main-image">
    </div>
    {% endif %}
    <div class="col">
        <h2>{{ ad.title }}</h2>
        <p>{{ ad.content }}</p>
        <p>{{ ad.contacts }}</p>
        <p class="text-end fst-italic">Добавлено {{ ad.created_at }}</p>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div class="d-flex justify-content-center align-items-center">
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'board:category_ads' pk=ad.category.pk %}{{ all }}">
      Назад</a></p>
<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Добавить' %}
</form>
{% if comments %}
<div class="vstack gap-3 mt-5">
    {% for comment in comments %}
    <div class="p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-end fst-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/category_ads.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}{{ category }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ category }}</h2>
<form class="row row-cols-md-auto justify-content-end">
    {% bootstrap_field form.keyword show_label=False wrapper_class='col-12' %}
    <div class="col-12">
        {% bootstrap_button 'Искать' %}
    </div>
</form>
{% if ads %}
<div class="vstack gap-3 my-4">
    {% for ad in ads %}
    <div class="card">
        {% url 'board:ad_detail' category_pk=category.pk pk=ad.pk as url %}
        <div class="row p-3">
            <a class="col-md-2" href="{{ url }}{{ all }}">
                {% if ad.image %}
                <img class="img-fluid" src="{% thumbnail ad.image 'default' %}">
                {% else %}
                <img class="img-fluid" src="{% static 'main/none-img.jpg' %}">
                {% endif %}
            </a>
            <div class="col-md-10 card-body">
                <h3 class="card-title"><a href="{{ url }}{{ all }}">
                    {{ ad.title }}</a></h3>
                <div class="card-text mb-2">{{ ad.content }}</div>
                <p class="card-text text-end fst-italic">{{ ad.created_at }}</p>
                <p class="card-text text-end fst-italic">С уважением, {{ ad.category }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/index.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
{% if ads %}
<h2>Последние объявления</h2>
<div class="vstack gap-3 mt-4 mb-4">
    {% for ad in ads %}
    <div class="card">
        {% url 'board:ad_detail' category_pk=ad.category.pk pk=ad.pk as url %}
        <div class="row p-3">
            <a class="col-md-2" href="{{ url }}{{ all }}">
                {% if ad.image %}
                <img class="img-fluid" src="{% thumbnail ad.image 'default' %}">
                {% else %}
                <img class="img-fluid" src="{% static 'main/none-img.jpg' %}">
                {% endif %}
            </a>
            <div class="col-md-10 card-body">
                <h3 class="card-title"><a href="{{ url }}{{ all }}">{{ ad.title }}</a></h3>
                <div class="card-text mb-2">{{ ad.content }}</div>
                <p class="card-text text-end fst-italic">{{ ad.created_at }}</p>
                <p class="card-text text-end fst-italic">С уважением, {{ ad.category }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/login.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_button 'Войти' %}
</form>
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/password_edit.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сменить пароль' %}
</form>
{% endblock %}

Call_Board/CallBoard/board/templates/main/profile_ad_detail.html
{% extends 'layout/basic.html' %}

{% block title %}{{ ad.title }} - {{ ad.category.name }}{% endblock %}

{% block content %}
<div class="row mt-3">
    {% if ad.image %}
    <div class="col-md-auto">
        <img src="{{ ad.image.url }}" class="main-image">
    </div>
    {% endif %}
    <div class="col">
        <h2>{{ ad.title }}</h2>
        <p>{{ ad.content }}</p>
        <p>{{ ad.contacts }}</p>
        <p class="text-end fst-italic">Добавлено {{ ad.created_at }}</p>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div class="d-flex justify-content-center align-items-center">
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'board:profile' %}">Назад</a></p>
{% if comments %}
<div class="vstack gap-3 mt-5">
    {% for comment in comments %}
    <div class="p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-end fst-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/profile_delete.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_button 'Удалить' button_class='btn-danger' %}
</form>
{% endblock %}

Call_Board/CallBoard/board/templates/main/profile_edit.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

Call_Board/CallBoard/board/templates/main/profile_old.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'board:profile_ad_add' %}">Добавить объявление</a></p>
{% if ads %}
<h3>Ваши объявления</h3>
<div class="vstack gap-3 mt-4 mb-4">
    {% for ad in ads %}
    <div class="card">
        {% url 'board:profile_ad_detail' pk=ad.pk as url %}
        <div class="row p-3">
            <a class="col-md-2" href="{{ url }}">
                {% if ad.image %}
                <img class="img-fluid" src="{% thumbnail ad.image 'default' %}">
                {% else %}
                <img class="img-fluid" src="{% static 'main/none-img.jpg' %}">
                {% endif %}
            </a>
            <div class="col-md-10 card-body">
                <h3 class="card-title"><a href="{{ url }}">{{ ad.title }}</a></h3>
                <div class="card-text mb-2">{{ ad.content }}</div>
                <p class="card-text text-end fst-italic">{{ ad.created_at }}</p>
                <p class="card-text text-end">
                    <a href="{% url 'board:profile_ad_edit' pk=ad.pk %}">Исправить</a>
                    <a href="{% url 'board:profile_ad_delete' pk=ad.pk %}">Удалить</a>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

Call_Board/CallBoard/board/templates/main/register.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Зарегистрироваться' %}
</form>
{% endblock %}